// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUXJl9-NUp7nuW0S4iWWaOw5rmYmgZZnY',
    appId: '1:688118703124:android:438d8b8acf1f1cf6463301',
    messagingSenderId: '688118703124',
    projectId: 'edutrack-2e971',
    storageBucket: 'edutrack-2e971.firebasestorage.app',
  );

  

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCooRQcnZQDQvQr7AiZoqgQAlWyaB8yvg',
    appId: '1:688118703124:web:514c061e01c35381463301',
    messagingSenderId: '688118703124',
    projectId: 'edutrack-2e971',
    authDomain: 'edutrack-2e971.firebaseapp.com',
    storageBucket: 'edutrack-2e971.firebasestorage.app',
    measurementId: 'G-C9GZ8L4SSJ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCijqS5RUhH95wrGjqeuIuCqLo9rxt5KYA',
    appId: '1:688118703124:ios:befef59ea1799626463301',
    messagingSenderId: '688118703124',
    projectId: 'edutrack-2e971',
    storageBucket: 'edutrack-2e971.firebasestorage.app',
    androidClientId: '688118703124-9un3f4brko8rrl032cu2ggijhhtflsmb.apps.googleusercontent.com',
    iosClientId: '688118703124-408bi5b4mm728a647t61rk8205hrm3u2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduTrackProject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCijqS5RUhH95wrGjqeuIuCqLo9rxt5KYA',
    appId: '1:688118703124:ios:befef59ea1799626463301',
    messagingSenderId: '688118703124',
    projectId: 'edutrack-2e971',
    storageBucket: 'edutrack-2e971.firebasestorage.app',
    androidClientId: '688118703124-9un3f4brko8rrl032cu2ggijhhtflsmb.apps.googleusercontent.com',
    iosClientId: '688118703124-408bi5b4mm728a647t61rk8205hrm3u2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduTrackProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCooRQcnZQDQvQr7AiZoqgQAlWyaB8yvg',
    appId: '1:688118703124:web:34348c8190680a5a463301',
    messagingSenderId: '688118703124',
    projectId: 'edutrack-2e971',
    authDomain: 'edutrack-2e971.firebaseapp.com',
    storageBucket: 'edutrack-2e971.firebasestorage.app',
    measurementId: 'G-4P6DSE1FN2',
  );

}